### ISSUE TITLE
Allow supressing debugCookies()

### ISSUE THREAD

**Issue by lolli42** [Codeception/module-webdriver#110]
Method `WebDriver->setCookie()` has an argument to suppress `debugCookies()`.

Methods `seeCookie()`, `dontSeeCookie()`, `resetCookie()` and `loadSessionSnapshot()` don't provide this.

We're using a helper to set cookies for quick access of our login restricted things and the cookie output is kinda noisy, which we'd like to suppress.

I could come up with a quite simple PR to add this. Do you think this would find general acceptance?

**Comment by Naktibalda** [comment]
`setCookie` parameter was added in https://github.com/Codeception/Codeception/pull/5709 to fix a similar issue with `loadSessionSnapshot`.

Adding `$showDebug` parameter to all cookie methods is a bit ugly, but I don't have any better ideas, so please raise the pull request.

**Comment by lolli42** [comment]
Cool thing. Happy thanks!
