### ISSUE TITLE
WebDriver::xpathLiteral() must be an instance of Codeception\Module\string, string given

### ISSUE THREAD

**Issue by slaFFik** [Codeception/module-webdriver#14]
When I try to run a test using `lucatume/wp-browser` with a super basic test having only this: `$I->loginAsAdmin();`.

```
[PHPUnit_Framework_Exception] Argument 1 passed to Codeception\Module\WebDriver::xpathLiteral() must be an instance of Codeception\Module\string, string given, called in ...\wp-content\plugins\
.vendor\codeception\module-webdriver\src\Codeception\Module\WebDriver.php on line 1100 and defined
```

**Comment by Naktibalda** [comment]
This issue was fixed in module-webdriver 1.0.5, upgrade your dependencies.

https://github.com/Codeception/module-webdriver/commit/d2be4dbdb6fe32ea08c30a716c4fda043c5eeebf
