### ISSUE TITLE
Docs: Drop Selenium and PhantomJS?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-webdriver#28]
The docs should give clear recommendations about which tools are best.
* @DavertMik told me already 3 years ago that PhantomJS is deprecated (https://github.com/Codeception/Codeception/pull/4267#discussion_r118913330). But it's still mentioned at https://codeception.com/docs/modules/WebDriver#PhantomJS. So my question is: Either remove it completely from the docs? Or just add a *big* caution box?
* Regarding Selenium I'm not up to date, so my question is: Is anybody still using Selenium Standalone Server (see https://codeception.com/docs/modules/WebDriver#Selenium)? Or everybody Chrome Driver directly? What would be the advantages of using Selenium Standalone? What about GeckoDriver, can it be used directly too?

**Comment by DavertMik** [comment]
> Either remove it completely from the docs? Or just add a big caution box?

Yes, we should remove it. Could you send PR to docs removing it?

> Is anybody still using Selenium Standalone Server

Yes

> Or everybody Chrome Driver directly?

I didn't have a good experience with it

**Comment by ThomasLandauer** [comment]
At the WordPress page, the entire example is based on PhantomJS. Please change that yourself - I haven't used this ever :-)

**Comment by ThomasLandauer** [comment]
> I didn't have a good experience with it

Do you mean you don't have *much* experience with it? Or *bad* experience (i.e. didn't work for you)?

What I don't really understand: The communication flow is between php-webdriver and ChromeDriver. How can it be that this gets better when adding an additional intermediate (Selenium)?

**Comment by Naktibalda** [comment]
PhantomJS was removed from docs, but `isPhantom` is still used in various methods and there is `phantomjs` environment in web.suite.yaml

**Comment by ThomasLandauer** [comment]
What is `web.suite.yaml`? Do you mean `acceptance.suite.yml`?
And do you mean the environment still exists there *in principle* or that it's (auto-)generated upon installation?
