### ISSUE TITLE
`getCurrentURL()` is not documented

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-webdriver#59]
Just noticed that `getCurrentURL()` (in `RemoteWebDriver`) is not mentioned at https://codeception.com/docs/modules/WebDriver

* What's the status/purpose of `RemoteWebDriver` at all? I mean: Why is it a separate file?
* Are all its methods available in WebDriver? => Then they should be merged automatically into https://codeception.com/docs/modules/WebDriver. Or are they left out on purpose?

**Comment by Naktibalda** [comment]
RemoveWebDriver is not part of this module, it belongs to php-webdriver library, which is used for communication with Selenium/Chromedriver/Geckodriver using WebDriver protocol
https://github.com/php-webdriver/php-webdriver/blob/main/lib/Remote/RemoteWebDriver.php

Methods of RemoveWebDriver are not exposed.
