### ISSUE TITLE
Recommend dbrekelmans/browser-driver-installer?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-webdriver#67]
I just stumbled over https://github.com/dbrekelmans/browser-driver-installer. Does anybody have any experiences?

We could recommend it as simpler(?) way of installation at https://codeception.com/docs/03-AcceptanceTests#WebDriver and/or https://codeception.com/docs/modules/WebDriver

**Comment by ThomasLandauer** [comment]
@Naktibalda Am I already going crazy, or did you indeed give a comment here, and delete it afterwards? ;-) Or was that somehwere else?

Anyway, just wanted to add that `hoa/console` (which is in `suggest` in https://github.com/Codeception/Codeception/blob/4.1/composer.json) lists in its `require` at https://github.com/hoaproject/Console/blob/master/composer.json:
```
"hoa/consistency": "dev-master",
"hoa/event"      : "dev-master",
"hoa/exception"  : "dev-master",
```
... which keep showing up in `composer outdated` like forever. So that's not very well-maintained either ;-)

**Comment by Naktibalda** [comment]
I found my comment at https://github.com/Codeception/module-webdriver/pull/69

And yes, hoa is abandoned - https://twitter.com/mnt_io/status/1207979302769348610

**Comment by DavertMik** [comment]
I added `selenium-standalone` as suggested installer
