### ISSUE TITLE
Please rebuild the docs page

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-webdriver#68]
I wanted to add some installation options from https://github.com/symfony/panther#installing-chromedriver-and-geckodriver, but https://github.com/Codeception/module-webdriver/pull/34 isn't online yet at https://codeception.com/docs/modules/WebDriver

**Comment by Naktibalda** [comment]
Docs build script fetches latest versions of all modules, this module had no releases since January.

**Comment by ThomasLandauer** [comment]
Oh, I see. Changing this might lead to some new function being explained on the website, which isn't released yet?! So the only way to "solve" this would be a dedicated docs release process, decoupled from the code releases? => And since this certainly isn't worth it, we just have to live with it... ;-)

**Comment by Naktibalda** [comment]
Actually it is the opposite, there is nothing else to release.
I tagged to new patch version and I will update documentation right away.

**Comment by Naktibalda** [comment]
https://codeception.com/docs/modules/WebDriver was updated.

**Comment by ThomasLandauer** [comment]
> Actually it is the opposite, there is nothing else to release.

Yeah, but only in this case here, not generally.

Anyway - thanks!
