### ISSUE TITLE
moveMouseOver Method phpdoc saying only css selector string but accept string/array css selector

### ISSUE THREAD

**Issue by Neila142** [Codeception/module-webdriver#70]
Hello,

Just used the module Webdriver module today and found than the phpdoc for **moveMouseOver** has for typehint

WebDriver.php: line 2804:
`
     * @param string $cssOrXPath css or xpath of the web element
`

But the example just above state than we can use it with the array selector `["css" => ".checkout"]`
I've tried running it with the array selector and it's working.

But my usage of `$I->moveMouseOver(["css" => ".checkout")` is marked as an phpstan error and could create other issue with other analysis tool.

**Comment by DerekCrannaford** [comment]
Seeing the same typehint causing problems during runtime of tests.

Code previously working as `$I->moveMouseOver(['css' => $category]);`
Is now throwing an error, halting tests:
`[TypeError] Argument 1 passed to ::moveMouseOver() must be of the type string or null, array given`

But Codeception documentation still states:
``` php
     * <?php
     * $I->moveMouseOver(['css' => '.checkout']);
     * $I->moveMouseOver(null, 20, 50);
     * $I->moveMouseOver(['css' => '.checkout'], 20, 50);
     * ```
