### ISSUE TITLE
VanillaJS: Alternative for jQuery `$.active`/ Count running `fetch` calls

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-webdriver#81]
After switching my Ajax calls from jQuery to `fetch`, this is not working anymore:
```php
$I->waitForJS("return $.active == 0;", 5);
```
Judging from https://stackoverflow.com/questions/33625485/equivalent-of-jquery-active-for-pure-javascript there's probably no quick solution :-( Any ideas anybody?

**Comment by Naktibalda** [comment]
This question is not an issue of WebDriver module.
