### ISSUE TITLE
Shadow DOM Support?

### ISSUE THREAD

**Issue by ryanknittel-fdx** [Codeception/module-webdriver#89]
#### What are you trying to achieve?

[`fillField`](https://codeception.com/docs/modules/WebDriver#fillfield) on an input within a shadow root.

Using xpath to locate the input within a shadow root fails as xpaths do not work with Shadow DOM.

I believe Shadow DOM can only be accessed using JavaScript.

I tried getting the element using JavaScript then binding the element to a PHP variable but that does not seem to be supported.

```php
$element = $I->executeJS('return document.evaluate(arguments[0], document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.shadowRoot.querySelector(arguments[1])', [ $prefix . "//app-datetime-picker", "input[name=shipped_date]" ]);
$I->fillFieldWhenAble($element, $value);
```

Results in error:

```bash
1) SomeTestSuiteCest: some Test
 Test  tests/acceptance/SomeTestSuite.php:someTest

  [PHPUnit\Framework\Exception] Array to string conversion at ../repo/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:2979


Scenario Steps:

 97. $I->fillFieldWhenAble({"element-6066-11e4-a52e-4f735466cecf":"71aa7ad4-9fe3-4839-a473-1f7f60099d45"},"11/11/2017") at SomeFile.php:403
```

Unfortunately, I cannot find any documentation about Shadow DOM or Shadow Root anywhere on codeception.com or this repository.

Any help with a workaround would be appreciated.

#### What do you get instead?

A `NoSuchElementException` error occurs:

```bash
[Facebook\WebDriver\Exception\NoSuchElementException] no such element: Unable to locate element: {"method":"xpath","selector":"//section[@id='fulfillments-sect-789-18013523-4074427']/div[@class='mini-form hybrid shipment-edit']/div[contains(@class,'panel-default')]/div[@class='panel-body']/form/div/div[contains(@class, 'ship-col')]//input[@name='shipped_date']"}
```

### Details

* Codeception version: 4.1.21
* PHP Version: 7.4
* Operating System: Linux

**Comment by ArcadeRenegade** [comment]
Thanks. Is it possible to assign a DOM element from executeJs or executeScript to a php variable then pass that variable in to an method like fillField with the new version? Does not seem supported looking at the codeception or php-webdriver documentation.

**Comment by Naktibalda** [comment]
You can't get DOM Element from Javascript in PHP, because it must be something that can be transferred via HTTP, so make your javascript code return string.

**Comment by ArcadeRenegade** [comment]
I attempted it as a workaround to get the element within the Shadow DOM and still be able to use the Codeception web driver APIs. So it seems like the only workaround is to re-create all the methods we use like click, fill, see element, get text, etc. as JavaScript in executeJS.

Unfortunately, that's not feasible for us but thank you for the help. If you want to close this ticket please feel free.
